name: Docker Image Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and Push Multi-Arch Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: xxradar/app:test
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: VERBOSE=true

    # Verify that the Docker image was built successfully
    - name: Verify Docker Image Build
      run: docker images | grep xxradar/app

    - name: Save Docker image as tar
      run: |
        mkdir -p image-artifact
        docker save xxradar/app:test > image-artifact/app-image.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image-artifact/app-image.tar
        retention-days: 7
        
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name app-container xxradar/app:test
        # Wait for the container to start
        sleep 5
        
    - name: Test root endpoint
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/)
        if [ "$response" -ne 200 ]; then
          echo "Root endpoint test failed with status code: $response"
          exit 1
        fi
        echo "Root endpoint test passed with status code: $response"
        
    - name: Test hello endpoint
      run: |
        response=$(curl -s http://localhost:8000/hello/GitHub)
        expected="{\"message\":\"Hello GitHub\"}"
        if [ "$response" != "$expected" ]; then
          echo "Hello endpoint test failed. Expected: $expected, Got: $response"
          exit 1
        fi
        echo "Hello endpoint test passed"
        
    - name: Check container logs
      if: always()
      run: docker logs app-container
      
    - name: Stop container
      if: always()
      run: docker stop app-container || true
